// Single source of truth for per-route <head> metadata.
//
// This module is PURE — it must not touch `document`, `window` or `localStorage`.
// Both the browser (via applyMeta) and the build-time prerenderer consume it, so the
// HTML a crawler reads and the metadata a visitor's tab shows can never drift apart.

import { BRAND_URL, SITE_URL, SITE_NAME, categorySlug } from './seo.js'
import { articles, categories } from '../data/articles.js'

const ORGANISATION = { '@type': 'Organization', name: 'OMIX Systems', url: `${BRAND_URL}/` }

const noindex = (title, description, url) => ({
  title,
  description,
  url,
  robots: 'noindex,follow',
  ogType: 'website',
  jsonLd: [],
})

/* Share cards are generated by scripts/generate-og.mjs into dist/og. Paths are
   stored relative and turned absolute by the head writers, so og:image is
   always a crawler-resolvable URL. */
const OG_DEFAULT = '/og/og-default.png'
const ogImage = (path, alt) => ({ image: path || OG_DEFAULT, imageAlt: alt })

/* Public lead-generation pages. Kept here (rather than in each component) so the
   prerendered HTML, the tab title and the sitemap can never disagree. */
const TOOL_PAGES = {
  '/quote': {
    title: `Website Quote Calculator — ${SITE_NAME}`,
    description:
      'Build an instant estimate for a website or business system: pick the features you need and see a real Kenyan-market price before you talk to anyone.',
    name: 'Website quote calculator',
  },
  '/audit': {
    title: `Free Business Audit — ${SITE_NAME}`,
    description:
      'Score your business\u2019s online presence in under a minute and find out what to fix first. Free, no card, no obligation.',
    name: 'Free business audit',
  },
  '/deal-alerts': {
    title: `Deal Alerts — ${SITE_NAME}`,
    description:
      'Get a message when prices drop on the OMIX Store in the categories and counties you actually shop in.',
    name: 'OMIX Store deal alerts',
  },
  '/referral': {
    title: `Refer and Earn — ${SITE_NAME}`,
    description:
      'Share your OMIX referral code: your friend gets KES 100 off their first order and you earn KES 100 when they shop.',
    name: 'OMIX referral programme',
  },
  '/sell': {
    title: `Sell on the OMIX Store — ${SITE_NAME}`,
    description:
      'Apply to sell on the OMIX marketplace and reach shoppers across all 47 Kenyan counties, with payments handled for you.',
    name: 'Sell on the OMIX Store',
  },
}

function toolMeta(path) {
  const page = TOOL_PAGES[path]
  const url = `${SITE_URL}${path}`
  return {
    title: page.title,
    description: page.description,
    url,
    robots: 'index,follow,max-image-preview:large,max-snippet:-1',
    ogType: 'website',
    ...ogImage(OG_DEFAULT, page.description),
    jsonLd: [
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: page.name,
        description: page.description,
        url,
        isPartOf: { '@type': 'WebSite', name: SITE_NAME, url: SITE_URL },
        publisher: ORGANISATION,
      },
    ],
  }
}

/**
 * Resolve a request path to its metadata.
 * Returns null for paths we deliberately do not prerender.
 */
export function getMeta(pathname) {
  const path = pathname.replace(/\/+$/, '') || '/'

  if (path === '/') return homeMeta()
  if (path === '/wiki') return wikiMeta(null)
  if (path.startsWith('/category/')) {
    const slug = decodeURIComponent(path.slice('/category/'.length))
    const name = categories.find(c => categorySlug(c) === slug)
    return wikiMeta(name || null, path)
  }
  if (path.startsWith('/wiki/') || path.startsWith('/articles/')) {
    const slug = decodeURIComponent(path.split('/').filter(Boolean).pop())
    return articleMeta(slug) || notFoundMeta()
  }
  if (TOOL_PAGES[path]) return toolMeta(path)
  if (path.startsWith('/admin')) {
    return noindex(
      'Admin — OMIX Journal',
      'Private administrative area.',
      `${SITE_URL}${path}`
    )
  }
  return notFoundMeta()
}

function notFoundMeta() {
  return noindex(
    `Page not found — ${SITE_NAME}`,
    'The page you requested does not exist or may have moved.',
    `${SITE_URL}/`
  )
}

function homeMeta() {
  const url = `${SITE_URL}/`
  const title = 'OMIX Journal — Engineering, Architecture & Product Notes'
  const description =
    'The OMIX Journal is a knowledge base covering software engineering, architecture, cloud systems, product development and business technology.'
  return {
    title,
    description,
    url,
    robots: 'index,follow,max-image-preview:large,max-snippet:-1',
    ogType: 'website',
    ...ogImage(OG_DEFAULT, 'OMIX Journal — practical notes on software, systems and products'),
    jsonLd: [
      {
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: SITE_NAME,
        url: SITE_URL,
        description,
        publisher: ORGANISATION,
      },
    ],
  }
}

function wikiMeta(categoryName, explicitPath) {
  const title = categoryName ? `${categoryName} — ${SITE_NAME}` : `Knowledge Base — ${SITE_NAME}`
  const description = categoryName
    ? `OMIX Journal articles about ${categoryName.toLowerCase()}, software engineering and digital products.`
    : 'Engineering notes, product thinking, business technology and practical software architecture from OMIX.'
  const url = explicitPath
    ? `${SITE_URL}${explicitPath}`
    : categoryName
      ? `${SITE_URL}/category/${categorySlug(categoryName)}`
      : `${SITE_URL}/wiki`
  const visible = categoryName ? articles.filter(a => a.category === categoryName) : articles
  return {
    title,
    description,
    url,
    robots: 'index,follow,max-image-preview:large,max-snippet:-1',
    ogType: 'website',
    ...(categoryName
      ? ogImage(`/og/category-${categorySlug(categoryName)}.png`, `${categoryName} — ${visible.length} notes in the OMIX Journal`)
      : ogImage(OG_DEFAULT, 'The OMIX Journal knowledge base')),
    jsonLd: [
      {
        '@context': 'https://schema.org',
        '@type': 'CollectionPage',
        name: title,
        description,
        url,
        isPartOf: { '@type': 'WebSite', name: SITE_NAME, url: SITE_URL },
        mainEntity: {
          '@type': 'ItemList',
          itemListElement: visible.map((a, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            url: `${SITE_URL}/wiki/${a.slug}`,
            name: a.title,
          })),
        },
      },
    ],
  }
}

function articleMeta(slug) {
  const article = articles.find(a => a.slug === slug)
  if (!article) return null

  const url = `${SITE_URL}/wiki/${article.slug}`
  return {
    title: `${article.title} — ${SITE_NAME}`,
    description: article.excerpt,
    url,
    robots: 'index,follow,max-image-preview:large,max-snippet:-1',
    ogType: 'article',
    ...ogImage(`/og/wiki-${article.slug}.png`, `${article.title} — ${article.category} note from the OMIX Journal`),
    publishedTime: article.date,
    section: article.category,
    jsonLd: [
      {
        '@context': 'https://schema.org',
        '@type': 'BlogPosting',
        headline: article.title,
        description: article.excerpt,
        datePublished: article.date,
        dateModified: article.date,
        inLanguage: 'en',
        author: ORGANISATION,
        publisher: ORGANISATION,
        mainEntityOfPage: { '@type': 'WebPage', '@id': url },
        articleSection: article.category,
        keywords: [article.category, 'OMIX', 'software engineering', 'digital products'],
      },
      {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Knowledge Base', item: `${SITE_URL}/wiki` },
          { '@type': 'ListItem', position: 2, name: article.category, item: `${SITE_URL}/category/${categorySlug(article.category)}` },
          { '@type': 'ListItem', position: 3, name: article.title, item: url },
        ],
      },
    ],
  }
}

/** Every path the prerenderer should emit as a static file. */
export function getPrerenderPaths() {
  const paths = ['/', '/wiki', ...Object.keys(TOOL_PAGES)]
  for (const c of categories) paths.push(`/category/${categorySlug(c)}`)
  for (const a of articles) paths.push(`/wiki/${a.slug}`)
  return paths
}